import Link from 'next/link'
import { Button } from './button'
import { CheckCircle, AlertCircle, FileText, Shield } from 'lucide-react'
import { TermsAcceptance } from './terms-acceptance'
import { useState } from 'react'

interface TermsRequiredProps {
  onAccept: (accepted: boolean) => void
  className?: string
}

export function TermsRequired({ onAccept, className = '' }: TermsRequiredProps) {
  const [termsAccepted, setTermsAccepted] = useState(false)

  const handleAccept = () => {
    if (termsAccepted) {
      onAccept(true)
    }
  }

  return (
    <div className={`min-h-screen flex items-center justify-center bg-gradient-to-br from-gray-100 to-gray-300 p-4 ${className}`}>
      <div className="bg-white rounded-2xl shadow-2xl p-8 max-w-2xl w-full">
        <div className="text-center mb-8">
          <div className="flex justify-center mb-4">
            <div className="bg-blue-100 p-3 rounded-full">
              <Shield className="w-8 h-8 text-blue-600" />
            </div>
          </div>
          <h1 className="text-3xl font-bold text-gray-900 mb-2">
            Welcome to my chatbot app
          </h1>
          <p className="text-gray-600 text-lg">
            Before you can start using our AI-powered document chat, please review and accept our terms.
          </p>
        </div>

        <div className="bg-gray-50 rounded-lg p-6 mb-6">
          <div className="flex items-center mb-4">
            <FileText className="w-5 h-5 text-gray-600 mr-2" />
            <h2 className="text-lg font-semibold text-gray-900">
              Important Information
            </h2>
          </div>
          <ul className="text-gray-700 space-y-2 text-sm">
            <li>• We do not store your original files - only extracted text</li>
            <li>• We do not collect personal information (emails, names, IPs)</li>
            <li>• Authentication is handled securely through Auth0</li>
            <li>• You are responsible for the content you upload</li>
            <li>• Do not upload sensitive, legal, or medical documents</li>
            <li>• <strong>Chatbot responses are generated by OpenAI's external servers</strong></li>
            <li>• Your questions and document content are sent to OpenAI for processing</li>
            <li>• OpenAI may use this data according to their privacy policy</li>
          </ul>
        </div>

        <div className="space-y-4 mb-6">
          <div className="flex justify-center space-x-4">
            <Link 
              href="/terms" 
              className="inline-flex items-center px-4 py-2 text-blue-600 hover:text-blue-800 underline"
              target="_blank"
            >
              <FileText className="w-4 h-4 mr-2" />
              Terms of Service
            </Link>
            <Link 
              href="/privacy" 
              className="inline-flex items-center px-4 py-2 text-blue-600 hover:text-blue-800 underline"
              target="_blank"
            >
              <Shield className="w-4 h-4 mr-2" />
              Privacy Policy
            </Link>
          </div>
        </div>

        <div className="mb-6">
          <TermsAcceptance 
            onAccept={setTermsAccepted}
            required={true}
          />
        </div>

        <div className="text-center">
          <Button 
            onClick={handleAccept}
            disabled={!termsAccepted}
            className="bg-blue-600 hover:bg-blue-700 disabled:bg-gray-400 disabled:cursor-not-allowed text-white font-semibold px-8 py-3 rounded-xl text-lg transition-all"
          >
            <CheckCircle className="w-5 h-5 mr-2" />
            Accept and Continue
          </Button>
        </div>

        <div className="mt-6 text-center">
          <p className="text-sm text-gray-500">
            By accepting, you agree to our Terms of Service and Privacy Policy.
          </p>
        </div>
      </div>
    </div>
  )
} 